### Autostart configuration
#
## background stuf mostly
exec_always {
  #notifications
	killall dunst
	dunst -conf $HOME/.config/dunst/dunstrc/mocha.conf
}
#keyring
exec gnome-keyring-daemon --start --components=secrets

#foot
exec foot --server 

#thunar daemon
exec thunar --daemon

# bitwarden
exec bitwarden-desktop

#for fingerprint popup
exec export SSH_AUTH_SOCK
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 

exec systemctl import-environment SWAYSOCK

# cliphist

exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
