### Idle configuration

exec_always swayidle -w \
		timeout 600 'swaylock -f \
			--indicator \
			--grace-no-mouse \
			--clock \
			--datestr "%Y-%m-%d" \
			--text-color cdd6f4 \
			--inside-color 1e1e2e \
			--inside-clear-color f38ba8 \
			--screenshot \
			--effect-blur 7x7 \
			--ring-color cba6f7 \
			--key-hl-color ffffff88 \
			--bs-hl-color ffaaaaff \
			--grace 5 \
			--fade-in 0.2' \
		timeout 1200 'swaymsg "output * power off"' \
		     resume 'swaymsg "output * power on"' \
		before-sleep 'swaylock -f \
			--color 1e1e2e \
			--indicator \
			--clock \
			--datestr "%Y-%m-%d" \
			--text-color cdd6f4 \
			--inside-color 1e1e2e \
			--inside-clear-color f38ba8 \
			--ring-color cba6f7 \
			--key-hl-color ffffff88 \
			--bs-hl-color ffaaaaff;'
