set $mod Mod4

# Layout stuff:
#
    # You can "split" the current object of your focus with
    # $mod+b or $mod+v, for horizontal and vertical splits
    # respectively.
    bindsym $mod+b splith
    bindsym $mod+v splitv

    # Switch the current container between different layout styles
    bindsym $mod+s layout stacking
    bindsym $mod+w layout tabbed
    bindsym $mod+e layout toggle split

    # Make the current focus fullscreen
    bindsym $mod+f fullscreen

    # Toggle the current focus between tiling and floating mode
    bindsym $mod+Shift+space floating toggle

    # Swap focus between the tiling area and the floating area
    bindsym $mod+space focus mode_toggle

    # Move focus to the parent container
    bindsym $mod+a focus parent
#



set $pawob wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/[^0-9]//g' > $WOBSOCK

bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym XF86AudioRaiseVolume exec (wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+ && $pawob)
bindsym XF86AudioLowerVolume exec wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%- && $pawob
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioPrev exec playerctl previous
# gimmick
bindsym $mod+XF86AudioMedia exec VirtualBoxVM --startvm "Windows XP"
bindsym XF86AudioNext exec playerctl next
bindsym XF86MonBrightnessDown exec brillo -q -u 50000 -U 1 && brillo -G | cut -d'.' -f1 > $WOBSOCK
bindsym XF86MonBrightnessUp exec brillo -q -u 50000 -A 1 && brillo -G | cut -d'.' -f1 > $WOBSOCK
bindsym Shift+XF86MonBrightnessDown exec brillo -u 50000 -U 2 && brillo -G | cut -d'.' -f1 > $WOBSOCK
bindsym Shift+XF86MonBrightnessUp exec brillo -u 50000 -A 2 && brillo -G | cut -d'.' -f1 > $WOBSOCK

# script not in dotfiles
bindsym Print exec /home/caiden/Scripts/screenshot
bindsym $mod+Shift+d exec firefox
bindsym $mod+Shift+s exec thunderbird
bindsym $mod+Shift+f exec thunar
# doesnt work rn, and not in my dotfiles yet
bindsym $mod+m exec /home/caiden/Scripts/short

bindsym $mod+Shift+v exec footclient -m -w 1228x1000 -T "Clipboard History" -e sh -c "cliphist list | fzf --no-sort | cliphist decode | wl-copy"

# these broke something
#bindswitch --reload --locked lid:on output eDP-1 disable
#bindswitch --reload --locked lid:off output eDP-1 enable
