#colors
#border
#background
#text
#indicator
#child border
client.unfocused \
"#606079" \
"#141415" \
"#cdcdcd" \
"#ff0000" \
"#1c1c24" 
client.focused \
"#e0a363" \
"#f3be7c" \
"#141415" \
"#e0a363" \
"#e0a363"
client.focused_tab_title \
"#f3be7c" \
"#e0a363" \
"#141415"
client.focused_inactive \
"#878787" \
"#606079" \
"#141415" \
"#878787" \
"#606079" 

# cursor not included
seat seat0 xcursor_theme catppuccin-mocha-peach-cursors 48
exec_always {
    gsettings set org.gnome.desktop.interface cursor-theme 'catppuccin-mocha-peach-cursors'
    gsettings set org.gnome.desktop.interface cursor-size 48
		echo "Xcursor.theme: catppuccin-mocha-peach-cursors" | xrdb -merge
    echo "Xcursor.size: 48" | xrdb -merge
}
#seat seat0 xcursor_theme adwaita 48
