#colors
#border
#background
#text
#indicator
#child border
client.unfocused \
"#606079" \
"#141415" \
"#cdcdcd" \
"#ff0000" \
"#1c1c24" 
client.focused \
"#e0a363" \
"#f3be7c" \
"#141415" \
"#ff0000" \
"#e0a363"
client.focused_tab_title \
"#00ff00" \
"#e0a363" \
"#141415"
client.focused_inactive \
"#878787" \
"#606079" \
"#141415" \
"#ff0000" \
"#606079" 

# cursor not included
seat seat0 xcursor_theme catppuccin-mocha-peach-cursors 48
